---

- hosts: localhost
  #remote_user: root
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: please enter the target host IP
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: dynamically_created_hosts

- hosts: dynamically_created_hosts
  tasks:
  - name: Copy a powershell script to host
    win_copy:
      src: powershell.ps1
      dest: C:\
  - name: Run A powershell script
    win_shell: C:\powershell.ps1 >> C:\output.txt

#ansible-playbook -i hosts ansible_playbook.yml --extra-vars "target_host=54.84.119.105"
