---

- hosts: win
  #remote_user: root

  tasks:
  - name: Copy a powershell script to host
    win_copy:
      src: /home/ec2-user/ansible/powershell.ps1
      dest: C:\
  - name: Run A powershell script
    win_shell: C:\powershell.ps1 >> C:\output.txt